//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawIt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrawIt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is up-to-date.
        /// </summary>
        internal static string AppUpToDate {
            get {
                return ResourceManager.GetString("AppUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CapFlat {
            get {
                object obj = ResourceManager.GetObject("CapFlat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CapRound {
            get {
                object obj = ResourceManager.GetObject("CapRound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CapTriangle {
            get {
                object obj = ResourceManager.GetObject("CapTriangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        internal static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coordinaat {
            get {
                object obj = ResourceManager.GetObject("coordinaat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CurParallel {
            get {
                object obj = ResourceManager.GetObject("CurParallel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version.
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CursorNone {
            get {
                object obj = ResourceManager.GetObject("CursorNone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw arc.
        /// </summary>
        internal static string DrawArc {
            get {
                return ResourceManager.GetString("DrawArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw circle with midpoint.
        /// </summary>
        internal static string DrawCircle2 {
            get {
                return ResourceManager.GetString("DrawCircle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw circle through 3 points.
        /// </summary>
        internal static string DrawCircle3 {
            get {
                return ResourceManager.GetString("DrawCircle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw circle sector.
        /// </summary>
        internal static string DrawCircleSector {
            get {
                return ResourceManager.GetString("DrawCircleSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw circle segment.
        /// </summary>
        internal static string DrawCircleSegment {
            get {
                return ResourceManager.GetString("DrawCircleSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw dimension.
        /// </summary>
        internal static string DrawDimension {
            get {
                return ResourceManager.GetString("DrawDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw new ellipse.
        /// </summary>
        internal static string DrawEllips {
            get {
                return ResourceManager.GetString("DrawEllips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw line.
        /// </summary>
        internal static string DrawLine {
            get {
                return ResourceManager.GetString("DrawLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawn new {0}.
        /// </summary>
        internal static string DrawNewShape {
            get {
                return ResourceManager.GetString("DrawNewShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw parallel.
        /// </summary>
        internal static string DrawParallel {
            get {
                return ResourceManager.GetString("DrawParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw point.
        /// </summary>
        internal static string DrawPoint {
            get {
                return ResourceManager.GetString("DrawPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw tangent arc.
        /// </summary>
        internal static string DrawTangentArc {
            get {
                return ResourceManager.GetString("DrawTangentArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favicon1 {
            get {
                object obj = ResourceManager.GetObject("favicon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favicon2 {
            get {
                object obj = ResourceManager.GetObject("favicon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} no longer exists. Do you want to remove it from the recent list?.
        /// </summary>
        internal static string FileNoLongerExists {
            get {
                return ResourceManager.GetString("FileNoLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All suported file types|*.tek;*.ico;*.icon|Drawings|*.tek|Icons|*.ico;*.icon.
        /// </summary>
        internal static string FilterOpenTekening {
            get {
                return ResourceManager.GetString("FilterOpenTekening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing|*.tek.
        /// </summary>
        internal static string FilterSaveTekening {
            get {
                return ResourceManager.GetString("FilterSaveTekening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] grab {
            get {
                object obj = ResourceManager.GetObject("grab", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] grabbing {
            get {
                object obj = ResourceManager.GetObject("grabbing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconCirkel2 {
            get {
                object obj = ResourceManager.GetObject("IconCirkel2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconCirkel3 {
            get {
                object obj = ResourceManager.GetObject("IconCirkel3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconCirkelBoog {
            get {
                object obj = ResourceManager.GetObject("IconCirkelBoog", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconCirkelSegment {
            get {
                object obj = ResourceManager.GetObject("iconCirkelSegment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconEllips {
            get {
                object obj = ResourceManager.GetObject("iconEllips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconGeslotenKromme {
            get {
                object obj = ResourceManager.GetObject("IconGeslotenKromme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconKromme {
            get {
                object obj = ResourceManager.GetObject("IconKromme", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconLayers {
            get {
                object obj = ResourceManager.GetObject("iconLayers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconMaatlijn {
            get {
                object obj = ResourceManager.GetObject("iconMaatlijn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconPunt {
            get {
                object obj = ResourceManager.GetObject("IconPunt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconRechte {
            get {
                object obj = ResourceManager.GetObject("IconRechte", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconVeelhoek {
            get {
                object obj = ResourceManager.GetObject("IconVeelhoek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IcoonCirkelSector {
            get {
                object obj = ResourceManager.GetObject("IcoonCirkelSector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap load {
            get {
                object obj = ResourceManager.GetObject("load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0} points.
        /// </summary>
        internal static string MovePoints_fm {
            get {
                return ResourceManager.GetString("MovePoints_fm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent files.
        /// </summary>
        internal static string NoRecent {
            get {
                return ResourceManager.GetString("NoRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFileIcon {
            get {
                object obj = ResourceManager.GetObject("OpenFileIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place text.
        /// </summary>
        internal static string PlacedNewText {
            get {
                return ResourceManager.GetString("PlacedNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception of type &quot;{0}&quot; was thrown in the application. &quot;{1}&quot; Please inform us about the exception, this way we can solve the problem..
        /// </summary>
        internal static string ReportExceptionString {
            get {
                return ResourceManager.GetString("ReportExceptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart?.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} has changed. Do you want to save it?.
        /// </summary>
        internal static string SaveChangesX {
            get {
                return ResourceManager.GetString("SaveChangesX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates.
        /// </summary>
        internal static string SearchFailed {
            get {
                return ResourceManager.GetString("SearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tekst {
            get {
                object obj = ResourceManager.GetObject("tekst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tekst1 {
            get {
                object obj = ResourceManager.GetObject("tekst1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File.
        /// </summary>
        internal static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update process has been cancelled.
        /// </summary>
        internal static string UpdateCancelled {
            get {
                return ResourceManager.GetString("UpdateCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update complete. Do you want to restart the application?.
        /// </summary>
        internal static string UpdateCompleteRestart {
            get {
                return ResourceManager.GetString("UpdateCompleteRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        internal static string updating {
            get {
                return ResourceManager.GetString("updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
